{{- if and (not .Values.localstack.enabled) (not .Values.externalS3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externals3"  }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: backend
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.externalS3.endpoint }}
  endpoint:  {{ .Values.externalS3.endpoint | b64enc | quote }}
  {{- end }}
  bucketName: {{ .Values.externalS3.bucketName | b64enc | quote }}
  {{- if .Values.externalS3.region }}
  region: {{ .Values.externalS3.region | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalS3.accessKey }}
  accessKey: {{ .Values.externalS3.accessKey| b64enc | quote }}
  {{- end }}
  {{- if .Values.externalS3.secretKey }}
  secretKey: {{ .Values.externalS3.secretKey | b64enc | quote }}
  {{- end }}
{{- end }}
